# Generated by Django 4.1.4 on 2022-12-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management", "0003_alter_user_modified_at"),
        ("product_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("provider", models.CharField(max_length=250)),
                ("status", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping_process.orderdetail",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_management.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="payment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shopping_process.paymentdetail",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_management.user"
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_management.product",
                    ),
                ),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping_process.shoppingsession",
                    ),
                ),
            ],
        ),
    ]
