# Generated by Django 4.1.4 on 2023-03-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0017_customerrequest"),
        ("shopping_process", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="session_id",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user_id",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ShoppingSession",
        ),
    ]
