# Generated by Django 4.1.4 on 2022-12-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("telephone", models.IntegerField()),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("payment_type", models.CharField(max_length=250)),
                ("provider", models.CharField(max_length=250)),
                ("account_number", models.IntegerField()),
                ("expire", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("permanent_address", models.CharField(max_length=250)),
                ("correspondence_address", models.CharField(max_length=250)),
                ("city", models.CharField(max_length=250)),
                ("postal_code", models.CharField(max_length=250)),
                ("country", models.CharField(max_length=250)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.user",
                    ),
                ),
            ],
        ),
    ]
