# Generated by Django 4.1.4 on 2022-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_alter_user_id_alter_useraddress_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
