# Generated by Django 4.1.4 on 2022-12-13 16:23

from django.db import migrations
import django_iban.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_alter_user_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="swift_bic",
            field=django_iban.fields.SWIFTBICField(default="sdf", max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="account_number",
            field=django_iban.fields.IBANField(max_length=34),
        ),
    ]
