# Generated by Django 4.1.4 on 2022-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_userpayment_swift_bic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Unidentified")],
                default="0",
                max_length=1,
            ),
        ),
    ]
