# Generated by Django 4.1.4 on 2022-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0006_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
