# Generated by Django 4.1.4 on 2022-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0008_img_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="img",
            name="name",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
