# Generated by Django 4.1.4 on 2022-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_img_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="created_at",
            field=models.DateTimeField(
                default="2022-12-21T17:40:50.898566+00:00", editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpayment",
            name="created_at",
            field=models.DateTimeField(
                default="2022-12-21T17:41:07.566556+00:00", editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpayment",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
