# Generated by Django 4.1.4 on 2023-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0012_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
