# Generated by Django 4.1.4 on 2023-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0013_user_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
