# Generated by Django 4.1.4 on 2023-02-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_process", "0001_initial"),
        ("product_management", "0012_alter_product_shipping_method"),
        ("user_management", "0015_alter_user_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserProfile",
        ),
    ]
