# Generated by Django 4.1.4 on 2023-03-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0016_rename_user_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=10000)),
                ("message", models.TextField()),
                (
                    "attach_file",
                    models.ImageField(
                        blank=True, default="default.jpg", upload_to="contact_form"
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user_management.userprofile",
                    ),
                ),
            ],
        ),
    ]
