# Generated by Django 4.1.4 on 2022-12-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_management.productcategory",
                    ),
                ),
            ],
        ),
    ]
