# Generated by Django 4.1.4 on 2022-12-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0002_productsubcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_id",
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_management.productsubcategory",
            ),
            preserve_default=False,
        ),
    ]
