# Generated by Django 4.1.4 on 2022-12-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_management",
            "0003_remove_product_category_id_product_subcategory_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="productinventory",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="deleted_at",
        ),
    ]
