# Generated by Django 4.1.4 on 2022-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_management",
            "0004_remove_discount_deleted_at_remove_product_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="default.jpg", upload_to="product_image"
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(to="product_management.productimage"),
        ),
    ]
