# Generated by Django 4.1.4 on 2022-12-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0005_productimage_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_management.discount",
            ),
        ),
    ]
