# Generated by Django 4.1.4 on 2023-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0006_alter_product_discount_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="decimal",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
