# Generated by Django 4.1.4 on 2023-01-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0007_product_decimal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="decimal",
        ),
    ]
