# Generated by Django 4.1.4 on 2023-01-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0013_user_rating"),
        ("product_management", "0008_remove_product_decimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.user",
            ),
            preserve_default=False,
        ),
    ]
