# Generated by Django 4.1.4 on 2023-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0009_product_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_delivery", models.BooleanField(default=False)),
                ("free_return", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
