# Generated by Django 4.1.4 on 2023-02-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0010_shippingmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_management.shippingmethod",
            ),
        ),
    ]
