# Generated by Django 4.1.4 on 2023-03-11 11:30

from django.db import migrations, models
import product_management.models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0012_alter_product_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_number",
            field=models.PositiveIntegerField(
                default=product_management.models.generate_product_number
            ),
        ),
    ]
