# Generated by Django 4.1.4 on 2023-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0013_product_product_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="cost",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
